server:
  port: 8085
  shop:
    shop_seven:
      status:
        url: "http://localhost:8081/application/status"
      good:
        url: "http://localhost:8081/shop/good"
    shop_nine:
      status:
        url: "http://localhost:8082/application/status"
      good:
        url: "http://localhost:8082/shop/good"